DROP TABLE IF EXISTS dbo.EMPLOYEE_AUDIT_INFO
GO
CREATE TABLE dbo.EMPLOYEE_AUDIT_INFO
(
  ID			 INTEGER		NOT NULL
, FIRST_NAME	 VARCHAR(100)	NOT NULL
, LAST_NAME		 VARCHAR(100)	NOT NULL
, MANAGER_ID	 INTEGER		NULL
, COMPANY_ID	 INTEGER		NULL
, PHONE_NO		 VARCHAR(20)	NULL
, JOINING_DATE	 DATETIME		NOT NULL
, RELIEVING_DATE DATE			NULL
, SALARY		 DECIMAL(15, 2) NOT NULL
, DEPT_ID		 INTEGER		NOT NULL
, EFF_DATE		 DATETIME		NULL		DEFAULT(GETDATE())
, TERM_DATE		 DATETIME		NULL
, CONSTRAINT chk_Aud_phone_number CHECK (LEN(PHONE_NO) = 8) 
, CONSTRAINT chk_Aud_Salary		  CHECK (SALARY > 0)
, CONSTRAINT chk_Joining_Date CHECK (ISNULL(JOINING_DATE, '') > '' AND JOINING_DATE > '01/01/1900')
) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX idx_Employee_Audit_Info_1 ON dbo.EMPLOYEE_AUDIT_INFO (ID)
GO
CREATE NONCLUSTERED INDEX idx_Employee_Audit_Info ON dbo.EMPLOYEE_AUDIT_INFO (ID, DEPT_ID, MANAGER_ID, COMPANY_ID)
GO